"""empty message

Revision ID: 00c2b4180651
Revises: 
Create Date: 2023-04-15 17:38:36.987007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00c2b4180651'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('role_ids', sa.String(length=64), nullable=False),
    sa.Column('role_desc', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('creattime', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=12), nullable=False),
    sa.Column('sex', sa.Enum('男', '女', '保密'), nullable=False),
    sa.Column('state', sa.Enum('正常', '封禁'), nullable=False),
    sa.Column('birth', sa.Date(), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('mailbox', sa.String(length=32), nullable=False),
    sa.Column('userpic', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manager',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('creattime', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=12), nullable=False),
    sa.Column('sex', sa.Enum('男', '女', '保密'), nullable=False),
    sa.Column('birth', sa.Date(), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('mailbox', sa.String(length=32), nullable=False),
    sa.Column('userpic', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['role'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manager')
    op.drop_table('user')
    op.drop_table('role_item')
    op.drop_table('role')
    # ### end Alembic commands ###
