"""empty message

Revision ID: 053694c45379
Revises: f7f35917d5d1
Create Date: 2023-05-12 10:53:51.036663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '053694c45379'
down_revision = 'f7f35917d5d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('originId', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('posterImg', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cam', schema=None) as batch_op:
        batch_op.drop_column('posterImg')
        batch_op.drop_column('originId')

    # ### end Alembic commands ###
