"""empty message

Revision ID: 1183eb26e032
Revises: af7413fbfb1a
Create Date: 2023-05-10 16:00:28.340666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1183eb26e032'
down_revision = 'af7413fbfb1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cam',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tit', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.Column('origin', sa.Text(), nullable=False),
    sa.Column('like', sa.Integer(), nullable=False),
    sa.Column('dislike', sa.Integer(), nullable=False),
    sa.Column('clickcount', sa.Integer(), nullable=False),
    sa.Column('tag', sa.Text(), nullable=True),
    sa.Column('mainTag', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=256), nullable=True),
    sa.Column('city', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cam')
    # ### end Alembic commands ###
