"""empty message

Revision ID: 2894923289ad
Revises: c2033ef9fd5e
Create Date: 2023-05-11 11:29:03.958212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2894923289ad'
down_revision = 'c2033ef9fd5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('iframe', 'HLS'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cam', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
