"""empty message

Revision ID: 53970882248f
Revises: 68fbb2064e10
Create Date: 2023-05-12 18:01:21.057045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53970882248f'
down_revision = '68fbb2064e10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cam_tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cam_tag')
    # ### end Alembic commands ###
