"""empty message

Revision ID: 7579fab35697
Revises: ad442599be71
Create Date: 2023-05-13 20:46:42.379212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7579fab35697'
down_revision = 'ad442599be71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cam', schema=None) as batch_op:
        batch_op.drop_column('score')

    # ### end Alembic commands ###
