"""empty message

Revision ID: af7413fbfb1a
Revises: 
Create Date: 2023-05-10 15:54:55.401454

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af7413fbfb1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manager',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('creattime', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=12), nullable=False),
    sa.Column('sex', sa.Enum('男', '女', '保密'), nullable=False),
    sa.Column('birth', sa.Date(), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('mailbox', sa.String(length=32), nullable=False),
    sa.Column('userpic', mysql.LONGTEXT(), nullable=True),
    sa.ForeignKeyConstraint(['role'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mailbox')
    )
    op.drop_table('cam')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cam',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tit', mysql.TEXT(), nullable=False),
    sa.Column('source', mysql.TEXT(), nullable=False),
    sa.Column('desc', mysql.TEXT(), nullable=False),
    sa.Column('origin', mysql.TEXT(), nullable=False),
    sa.Column('like', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dislike', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('clickcount', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag', mysql.TEXT(), nullable=True),
    sa.Column('mainTag', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('country', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('manager')
    # ### end Alembic commands ###
