"""empty message

Revision ID: c2033ef9fd5e
Revises: 1183eb26e032
Create Date: 2023-05-11 11:14:28.801742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2033ef9fd5e'
down_revision = '1183eb26e032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postImg', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cam', schema=None) as batch_op:
        batch_op.drop_column('state')
        batch_op.drop_column('postImg')

    # ### end Alembic commands ###
