"""empty message

Revision ID: f7f35917d5d1
Revises: 2894923289ad
Create Date: 2023-05-12 10:48:57.677820

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f7f35917d5d1'
down_revision = '2894923289ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posterImgPath', sa.String(length=512), nullable=True))
        batch_op.drop_column('postImg')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postImg', mysql.VARCHAR(length=512), nullable=True))
        batch_op.drop_column('posterImgPath')

    # ### end Alembic commands ###
